//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVerduleria
{


    public partial class MantenimientoTipoProducto
    {

        /// <summary>
        /// Control forms.
        /// </summary>
        /// <remarks>
        /// Automatically generated field.
        /// To modify it, move the field declaration from the designer file to the code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm forms;

        /// <summary>
        /// Control txtNombreProducto.
        /// </summary>
        /// <remarks>
        /// Automatically generated field.
        /// To modify it, move the field declaration from the designer file to the code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNombreProducto;

        /// <summary>
        /// Control ListaTipoProducto.
        /// </summary>
        /// <remarks>
        /// Automatically generated field.
        /// To modify it, move the field declaration from the designer file to the code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ListaTipoProducto;

        /// <summary>
        /// Control ListaTipoPrecio.
        /// </summary>
        /// <remarks>
        /// Automatically generated field.
        /// To modify it, move the field declaration from the designer file to the code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ListaTipoPrecio;

        /// <summary>
        /// Control txtCantidad.
        /// </summary>
        /// <remarks>
        /// Automatically generated field.
        /// To modify it, move the field declaration from the designer file to the code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCantidad;

        /// <summary>
        /// Control txtPrecio.
        /// </summary>
        /// <remarks>
        /// Automatically generated field.
        /// To modify it, move the field declaration from the designer file to the code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtPrecio;

        /// <summary>
        /// Control btnGuardar.
        /// </summary>
        /// <remarks>
        /// Automatically generated field.
        /// To modify it, move the field declaration from the designer file to the code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
